//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::banner::Entity as Banner;
pub use super::block::Entity as Block;
pub use super::coins::Entity as Coins;
pub use super::price::Entity as Price;
pub use super::proposals::Entity as Proposals;
pub use super::relations::Entity as Relations;
