//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "proposals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub proposal_id: u64,
    pub address: String,
    pub token1_address: String,
    pub token2_address: String,
    pub token: String,
    pub liquidity: String,
    pub create_time: u32,
    pub close_time: u32,
    #[sea_orm(column_type = "Custom(\"ENUM ('NotReviewed','Passed','NotPassed')\".to_owned())")]
    pub audit_state: String,
    pub category: u32,
    #[sea_orm(column_type = "Custom(\"ENUM ('Original','Formal','End')\".to_owned())")]
    pub state: String,
    pub volume: String,
    pub volume24: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
